### ISSUE TITLE
Doesn't work the way it should work.

### ISSUE THREAD

**Issue by rpriyanshu9** [Sayegh7/move_to_background#5]
This is what I'm doing. Now when the user presses `back` in android, the app moves to background, but when i select it from there it restarts, rather than resuming from where i left it. How to solve this?

```
@override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        MoveToBackground.moveTaskToBack();
        return false;
      },
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Flutter Demo',
        darkTheme: ThemeData.dark(),
        themeMode: currentTheme.myCurrentTheme(),
        theme: ThemeData.light(),
        home: MyHomePage(),
      ),
    );
  }
```

**Comment by shashikantdurge** [comment]
@rpriyanshu9 Can you please send the device details?

**Comment by shaadart** [comment]
@shashikantdurge what do you think, what may be the problem?

**Comment by shashikantdurge** [comment]
@madd-project  I was going to figure out the issue with device details, it worked in OnePlus 3.

**Comment by shaadart** [comment]
Hellow @shashikantdurge ,
In my case, the `move_to_background` is working fine when the app is minimized, 
But not in the when I killed the Application, Do you think the package works fine when the app is killed. 

I would love to get your answers.
Also i am using Samsung j7 prime

**Comment by shashikantdurge** [comment]
It will not work when app is killed, it's an expected behaviour.

The purpose of the plugin is to take app to background without losing current app state onBackPressed

**Comment by madd-project** [comment]
🥇 @shashikantdurge 
Happy to see your Replies, 

Shashi Kant, I was looking for the alternative of the work manager, which could help me to run the app in the background, 
but I was not able to find a good one, Work manager just don't work well with Local Storages like Hive so I was Finding up one, 

I founded `move_to_background` it was really Helping me to run the app in the background, (in minimized mode)
But A user will not always make the app stay open in the recent tab,
So do you know across from this bridge?

**Comment by Sayegh7** [comment]
> It will not work when app is killed, it's an expected behaviour.
> 
> The purpose of the plugin is to take app to background without losing current app state onBackPressed

Couldn't have said it better myself. Feel free to reopen a new issue with more details if it's a bug in the plugin's expected behavior.
