### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by lulupointu** [Sayegh7/move_to_background#7]
Hi, Thanks for the package once again !

Could you publish a null-safety version of your package on pub.dev ?

**Comment by Sayegh7** [comment]
Hey @lulupointu, I already did publish it. It's just marked as a prerelease version

https://pub.dev/packages/move_to_background/versions/1.0.1-nullsafety.1

**Comment by lulupointu** [comment]
Oh nvm I did not see !

You should update the version to 1.0.2 though, otherwise we can't see the pre-release. See the difference bellow:

This is you package when we go to the default page
![image](https://user-images.githubusercontent.com/5128921/110631739-2417e780-81a7-11eb-849c-64bfe7d3e605.png)

This is another package which versioned properly
![image](https://user-images.githubusercontent.com/5128921/110631918-54f81c80-81a7-11eb-810b-0745a6ff26c3.png)

In any case thanks for the direct link !

**Comment by lulupointu** [comment]
Hi,

I'm sorry to insist but my package is relying on yours and I am loosing 10 pub points because of your naming. Could you please fix this? You could even release a 1.0.2 with nullsafety since it's now recommended to release null safe packages.

Thanks again and sorry to reopen this issue

**Comment by Sayegh7** [comment]
Released 1.0.2 👍
